#----------------------------------------#
version: '2'
#----------------------------------------#
services:
  #----------------------------------------#
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
      - ./app:/var/www/app
    depends_on:
      - php
  #----------------------------------------#
  php:
    container_name: php
    image: php:test
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/app
    depends_on:
      - mysql
  #----------------------------------------#
  mysql:
    container_name: mysql
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=StrongPassword
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
#----------------------------------------#